- name: "install accumulo from tarball"
  unarchive: src={{ tarballs_dir }}/{{ accumulo_tarball }} dest={{ install_dir }} creates={{ accumulo_home }} copy=yes
- name: "copy default accumulo configuration"
  command: cp {{ accumulo_home }}/conf/templates/{{ item }} {{ accumulo_home }}/conf/ creates={{ accumulo_home }}/conf/{{ item }}
  with_items:
    - accumulo-metrics.xml
    - auditLog.xml
    - monitor_logger.properties
    - monitor_logger.xml
    - log4j.properties
- name: "configure accumulo using managed files"
  copy: src={{ item }} dest={{ accumulo_home }}/conf/{{ item }}
  with_items:
    - generic_logger.properties
    - generic_logger.xml
- name: "configure accumulo using managed templates"
  template: src={{ item }} dest={{ accumulo_home }}/conf/{{ item }}
  with_items:
    - accumulo-env.sh
    - accumulo-site.xml
    - masters
    - slaves
    - gc
    - tracers
    - monitor
    - client.conf
    - hadoop-metrics2-accumulo.properties
- name: "build accumulo native libraries"
  shell: "{{ accumulo_home }}/bin/build_native_library.sh" 
  args: 
    creates: "{{ accumulo_home }}/lib/native/libaccumulo.so"
