- name: "add datasources"
  command: "curl http://admin:admin@{{ groups['metrics'][0] }}:3000/api/datasources -X POST -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{{item}}'"
  register: cresult
  until: cresult.rc == 0
  retries: 6
  delay: 5
  with_items:
    - '{"name":"cluster_metrics", "type":"influxdb", "url":"http://{{ groups["metrics"][0] }}:8086", "access":"direct", "isDefault":true, "database":"cluster_metrics", "user":"fluo", "password":"secret"}'
    - '{"name":"fluo_metrics", "type":"influxdb", "url":"http://{{ groups["metrics"][0] }}:8086", "access":"direct", "isDefault":true, "database":"fluo_metrics", "user":"fluo", "password":"secret"}'
    - '{"name":"accumulo_metrics", "type":"influxdb", "url":"http://{{ groups["metrics"][0] }}:8086", "access":"direct", "isDefault":true, "database":"accumulo_metrics", "user":"fluo", "password":"secret"}'
